- bql/planner/planner.go
- bql/planner/planner_test.go
The root of this bug seems to stem from the planner not registering the output bindings with the table before projecting, causing the table to throw an error that the output bindings are unknown. These changes register the output bindings with the table before projecting and copy the values for the input bindings to the output bindings for each row of the table. Tests and benchmarks are included. Also, query testing was modified so no additional testing is performed on a query with failed planner execution to avoid superfluous errors.
> Fix AS keyword bug

- triple/literal/literal.go
The error should report that the type of the value is not supported, not that the BadWolf literal type is unsupported.
> Correct error in literal builder

- bql/grammar/grammar.go
- bql/grammar/grammar_test.go
- bql/lexer/lexer.go
- bql/lexer/lexer_test.go
Also fixed some typos that I found.
> Issue 46: Parse Construct Statement

- bql/semantic/semantic.go
- bql/semantic/semantic_test.go
I want to make sure that the addition I am making to the `Statement` struct looks good.
> Added ConstructClause to Statement struct

- triple/node/node.go
- triple/node/node_test.go
I did not do too much of error checking in the Parse method since the lexer should check for valid blank nodes.
> Modifed Parse to handle Blank Nodes.

- bql/grammar/grammar.go
- bql/semantic/convert.go
- bql/semantic/hooks.go
- bql/semantic/hooks_test.go
- bql/semantic/semantic.go
- triple/node/node.go
- triple/triple.go
I have not added any tests yet. If this commit looks good on a high level, I will add tests before merging this branch.
> constructSubjectClause, constructPredicateClause and constructObjectClause

- bql/grammar/grammar.go
- bql/grammar/grammar_test.go
- bql/semantic/hooks.go
- bql/semantic/hooks_test.go
- bql/semantic/semantic.go
- bql/semantic/semantic_test.go
With this PR, construct clauses can be fully expressed via the `Statement` struct.
> Reification hooks and tests

- bql/grammar/grammar.go
- bql/grammar/grammar_test.go
- bql/planner/planner.go
- bql/planner/planner_test.go
- bql/semantic/hooks.go
- bql/semantic/hooks_test.go
- bql/semantic/semantic.go
- bql/semantic/semantic_test.go
This PR is to add input and output graph lists to the statement, along with the regular graph lists. The idea is to use the regular graph lists to collect graphs for creation/deletion, and the input graph lists to collect graphs that act as a source of information (such as information queried in a WHERE clause) and the output graph lists to collect graphs that act as a destination of information (such as triples added in an INSERT or CONSTRUCT clause).
There are a couple of reasons for this change. Primarily, there needs to be a distinction between input and output graphs in a CONSTRUCT...WHERE BQL statement. Also, having the distinction helps to reason through the code.
> Added input and output graph lists.

- bql/planner/planner.go
- bql/planner/planner_test.go
Fixed a bug introduced yesterday. The update() function needs to know which graph to add/remove triples to. I have updated the delete test to fail due to this bug and have ensured that it passed after the bug fix. Also, I have verified that delete triples works from the BW cli.
> Fixed delete triples bug

- bql/planner/planner.go
- bql/planner/planner_test.go
- bql/semantic/semantic.go
- bql/semantic/semantic_test.go
- bql/table/table.go
- tools/benchmark/batteries/add.go
- tools/benchmark/batteries/bql.go
- tools/benchmark/batteries/remove.go
- tools/compliance/runner.go
- tools/compliance/runner_test.go
- tools/vcli/bw/assert/assert.go
- tools/vcli/bw/benchmark/benchmark.go
- tools/vcli/bw/common/common.go
- tools/vcli/bw/repl/repl.go
- tools/vcli/bw/run/run.go
- tools/vcli/bw/server/server.go
The planner for the construct statement + tests. Also the triples loading for tests has been refactored so that all test cases can use a single method.
> Implemented planner for the CONSTRUCT statement.

- bql/grammar/grammar.go
- bql/grammar/grammar_test.go
- bql/planner/planner.go
- bql/semantic/hooks.go
- bql/semantic/hooks_test.go
- bql/semantic/semantic.go
- bql/semantic/semantic_test.go
- triple/triple.go
- triple/triple_test.go
Also cleaned up some test formatting. Mostly, this PR gets rid of massive amounts of duplicated code implementing the CONSTRUCT clause.
> Generalized Reification Clauses into Predicate-Object Pairs.

- bql/planner/planner_test.go
Hi,
In TestPlannerQuery, ctx is assigned as the 1st step of the test and then again to the same value right after the table allocation without using it in between.
This PR removes the 1st assignment (and some trailing spaces too).
Thanks,
Joseph
> minor: remove double assignment of ctx in TestPlannerQuery

- .travis.yml
- go.mod
- go.sum
Hi guys,
As it's been a bit over a year that the main projects have started to use the go modules, I figured that maybe it would be good to switch badwolf to use go modules too.
So here's the PR for it.
Note: it also switches travis to:
* use go modules
* test on go 1.12, 1.13 and tip (removes 1.11)
* adds the `-v -race` options to the tests to have better visibility and check for race conditions
* limit the depth of the tree cloning to 1 as we don't look at the history (makes the clone more efficient)
Thanks for your time,
Joseph
> Switch to go modules

- docs/bql.md
Hi,
This PR fix a few typos and tries to get a more homogeneous usage of backticks and `:` in the BQL documentation (Pretty nice doc by the way! :wink:  ).
Let me know if you want some of these suggestions changed.
Thanks,
Joseph
> Update and fix typos in the bql documentation

- bql/planner/planner_test.go
Hi guys,
I missed this last time I was looking at ineffassign.
ctx here is re-reclared on the next line so just cleaning up the first unused assignment.
Thanks,
Joseph
> Remove double assignment of ctx in benchmarkQuery

- bql/semantic/semantic.go
- bql/semantic/semantic_test.go
- triple/node/node.go
- triple/node/node_test.go
Hi guys,
In the current `ConstructPredicateObjectPair.String()` when we look for an object binding, whether `c.O` is nil or not we set object to true meaning that we just never enter the Predicate portion.
This will lead to only partially returning the representation of the object (leaving out the ID an the anchorBinding).
Plus in the predicate portion we already take care of printing the binding so basically it's doing twice the same thing.
Joseph
> Fix the string representation of a ConstructPredicateObjectPair and add more tests

- bql/grammar/grammar.go
- bql/planner/planner_test.go
- bql/semantic/expression.go
- bql/semantic/expression_test.go
- tools/benchmark/batteries/add.go
- tools/vcli/bw/load/load.go
This should make it possible the following clauses:
* HAVING NOT(?s = /_<some_id>)
* HAVING ?s > /_<some_id>)
etc...
> Implementing Having Clause for bindings and node literals.

- bql/grammar/grammar.go
- bql/grammar/grammar_test.go
- bql/lexer/lexer.go
- bql/planner/planner_test.go
- bql/semantic/hooks.go
- bql/semantic/hooks_test.go
As @xllora and @rbkloss were discussing about in #90 , the current syntax for the AFTER block does not reflect what the doc says it's supposed to be.
In fact the problem extends to the BEFORE and BETWEEN clauses too.
This PR changes the lexer and hook to behave as expected for those 3 clauses.
Note: I haven't added unit tests specific to the new lexer function as I think the higher level tests at the grammar and planner level already catch that but I can add more tests there if needed. Just let me know.
Closes: #90
> Fix syntax parsing of BEFORE, AFTER and BETWEEN clauses

- .github/workflows/tests.yml
- bql/table/table.go
This change adds the build of the bw command-line tool and the execution of the bql examples against it.
This gives us higher level testing capabilities for the CI.
> Run the bql examples as part of the CI process

- bql/planner/planner.go
Hi,
Currently we use the context of the errgroup only when checking the existence of the inputgraph (note: we don't seem to be doing anything with it concretely in the Exist method but that's a story for another time) but previously we had some "fail-fast" logic to avoid executing code when a failure already occurred (as we only cared about the data if there is no error).
This change avoids starting goroutines if other routines already started and aborts the filtering when an error already occurred in the errgroup. This might make sense if the clients properly check the error output every time and should improve the performance if we parse a lot of data with errors found early on (aka the performance gain might be really random).
At the beginning I thought this was handled magically …
> Abort early on pre-existing failures in filterOnExistence

- bql/lexer/lexer.go
- docs/bql.md
- triple/predicate/predicate.go
When using the keywords `AFTER`, `BEFORE` and `BETWEEN` to filter triples based on time bounds, the intervals defined by these keywords are closed intervals, which means that the limits of those intervals are also included. The documentation should reflect this specification.
> Add that the keywords AFTER, BEFORE and BETWEEN define closed intervals

- bql/grammar/grammar.go
The previous refactoring made all BQL objects share the same clause objects which caused data races.
This should keep the navigability benefits while making each BQL have specific non-shared clauses.
> Fixing grammar for navigability

- bql/planner/planner_test.go
- bql/semantic/expression.go
- bql/semantic/expression_test.go
- docs/bql.md
- triple/literal/literal.go
Previously, comparisons between ID bindings and text literals inside HAVING clauses (such as below) were not effective:
```
SELECT ?s, ?predID, ?o
FROM ?family
WHERE {
?s ?p ID ?predID ?o
}
HAVING ?predID < "parent_of"^^type:text;
```
Now, they are fully supported (`<`, `>` and `=`), proceeding as a lexicographical comparison between the ID binding and the text literal that follows.
The same is now supported for bindings created using the TYPE keyword too.
Error handling for comparison expressions were also improved.
> Fix support for comparison between ID/TYPE bindings and text literals inside HAVING clauses

- bql/planner/planner_test.go
- bql/semantic/expression_test.go
For clarity, it is useful to not mix in the same test function cases for which it is expected an error and cases for which it is not. 
Separating these cases into two different test functions makes the code cleaner and avoids the unnecessary use of more complicated `ifs` inside the body of the test function. Also, it makes it easier to add new test cases in the future as it is simpler to realize where they belong to in the test file.
Then, this PR comes to follow this guideline for two important test functions inside `expression_test.go` and `planner_test.go`.
> Refactor tests into separate functions that expect errors or not

- bql/planner/data_access.go
- bql/planner/planner_test.go
Previously, when extracting the TYPE of an object through a TYPE binding, you would find a **deadlock** and the program would freeze if you had objects that were not nodes in your graph. 
For example, in the graph `?family` with the following triples:
```
INSERT DATA INTO ?family {
/u<peter> "height_cm"@[2006-01-02T15:04:05.999999999Z] "172"^^type:int64 .
/u<joe> "height_cm"@[2006-01-02T15:04:05.999999999Z] "174"^^type:int64 .
/u<joe> "parent_of"@[] /u<peter>
};
```
If you executed the following query:
```
SELECT ?o_type
FROM ?family
WHERE {
/u<joe> ?p ?o TYPE ?o_type
};
```
You would have a deadlock due to the fact that your query would try to extract the TYPE from a literal object (eg: `"174"^^type:int64` here), that does not have a TYPE as in the case of a node object. It would also …
> Fix bug of TYPE bindings with non-node objects and AT bindings with immutable triples (Issue #113)

- bql/planner/data_access_test.go
- bql/planner/planner_test.go
Refactor `data_access_test.go` to make it cleaner, avoid repeated code (and multiple `if` clauses) and also use more clear variable names as a way of easing the job of anyone that may pass through or work on this file in the future.
> Refactor "data_access_test.go" for clarity and conciseness

- bql/grammar/grammar.go
- bql/grammar/grammar_test.go
Allow the user to do a single AT extraction just after an object binding (useful when the object is a predicate, in a reification scenario for example). To illustrate: 
```
SELECT ?p, ?o, ?o_time
FROM ?test
WHERE {
?s ?p ?o AT ?o_time
};
```
> Allow single AT extraction just after object binding in grammar

- bql/planner/data_access.go
Inside `addTriples` in "data_access.go", the short assignment `:=` was recreating a local version of the variable `err`. Then, the value eventually assigned to it was lost as soon as the `for` loop was finished (instead of keeping this value assigned to the `addTriples` scope level `err` variable). This PR comes to fix this problem.
> Fix problem with short variable assignment in "data_access.go"

- bql/grammar/grammar.go
- bql/grammar/grammar_test.go
- bql/lexer/lexer.go
- bql/lexer/lexer_test.go
- bql/planner/planner_test.go
- bql/semantic/expression.go
- bql/semantic/expression_test.go
If we extract a time binding inside the `WHERE` clause it would be useful to be able to use it for comparisons inside the `HAVING` clause, creating conditions around that binding. This PR comes to add support for this.
To illustrate, the query below is now possible:
```
SELECT ?p, ?time
FROM ?test
WHERE {
    /u<peter> ?p AT ?time ?o
}
HAVING ?time < 2016-03-01T00:00:00-08:00;
```
On which the time binding `?time` extracted with the `AT` keyword can now be compared to a time literal (`2016-03-01T00:00:00-08:00` above) inside the HAVING clause.
You can also combine it with `ID` bindings to create more complex conditions inside the `HAVING` clause:
```
SELECT ?s, ?p, ?p_id, ?time
FROM ?test
WHERE {
    ?s ?p ID ?p_id AT ?time ?o
}
HAVING (?p_id < "in"^^type:text) AND (?time > …
```
> Support time binding comparisons inside HAVING clauses

- bql/grammar/grammar.go
- bql/grammar/grammar_test.go
- bql/planner/planner_test.go
- bql/semantic/expression.go
- bql/semantic/expression_test.go
We can now compare a predicate binding to a predicate literal inside the `HAVING` clause (only equalities allowed) to filter the results of our query.
To illustrate, the following query is now possible:
```
SELECT ?s, ?p, ?o
FROM ?test
WHERE {
    ?s ?p ?o
}
HAVING ?p = "height_cm"@[];
```
Note that predicate inequalities are not allowed because their behavior may become confusing for the user (especially when time anchors come on stage). In this case an error is prompted orienting to extract bindings with the `ID`/`AT` keywords and to use these bindings to proceed with the comparisons in a clearer way.
> Support predicate binding equalities inside HAVING clauses

- bql/table/table.go
This conversion can take significant time depending on the size of aaps.
Since it doesn 't access any shared data, moved it out of the locked region
> convert aaps to map outside of the locked region 

- bql/grammar/grammar.go
- bql/grammar/grammar_test.go
- bql/planner/planner_test.go
This PR come as a response for the Issue https://github.com/google/badwolf/issues/106.
After testing with the [SPARQL playground](http://sparql-playground.sib.swiss/) and two other online UIs, and looking at the [SPARQL - W3C Recommendation](https://www.w3.org/TR/rdf-sparql-query/), it was noted that with SPARQL the trailing dots are mandatory at the end of each clause inside `WHERE`, with the exception of the last clause (after which the dot is optional).
Then, as it was decided to follow the W3C SPARQL recommendation as close as possible, this PR comes to make BQL have the same behavior pointed above: mandatory trailing dots at the end of each clause inside `WHERE` with the exception of the last one (after which the dot will be optional).
To illustrate, given the query below:
```
SELECT …
```
> Make trailing dot optional after the last clause inside WHERE

- bql/planner/planner_test.go
- bql/semantic/expression.go
- bql/semantic/expression_test.go
From now on, comparisons between a node binding and a node literal inside `HAVING` clauses can only be equalities, such as in:
```
SELECT ?s, ?height
FROM ?test
WHERE {
?s "height_cm"@[] ?height
}
HAVING ?s = /u<bob>;
```
Note that node inequalities are not allowed anymore because they may raise confusion with regards to what is indeed being compared (only the `ID`, only the `TYPE`, or both together).
In the case of inequalities an error is prompted orienting the user to extract bindings with the `ID`/`TYPE` keywords and to use these bindings to proceed with the comparisons in a clearer way.
> Add instructing error messages in the case of node binding inequalities inside HAVING clauses

- bql/planner/data_access.go
- bql/planner/data_access_test.go
- bql/planner/planner_test.go
We have two types of time bindings: `AT` bindings (using the `AT` keyword) and time anchor bindings (eg: `"bought"@[?time]`). 
In both cases, if a graph pattern tries to extract the time anchor from a non-predicate object (like when the object is a node such as `/u<eve>` or a literal such as `"174"^^type:int64`) we want to skip this triple and do not show it in the query result (as it does not precisely match the exact graph pattern specified - the pattern required a time anchor in a predicate object). 
Nevertheless, there is one exception: if this graph pattern is marked as `OPTIONAL` we expect to see `<NULL>` in the query result for that time binding. 
This PR, then, comes to enforce this behavior.
To illustrate for the case of an `AT` binding, take the query below:
```
SELECT ?s, ?o, …
```
> Adjust behavior of time bindings for non-predicate objects

- bql/planner/data_access.go
- bql/planner/data_access_test.go
- bql/planner/planner_test.go
In the case of `TYPE` bindings for non-node objects we want to skip this triple and do not show it in the query result as it does not precisely match the exact graph pattern specified (the pattern required a `TYPE` extraction, therefore the object had to be a node).
Nevertheless, there is one exception: if this graph pattern is marked as `OPTIONAL` we expect to see `<NULL>` in the query result for that `TYPE` binding.
This PR, then, comes to enforce this behavior.
In other words, if the object is a predicate or a literal we will not succeed in extracting the node type using the `TYPE` keyword and so we skip the triple if the clause is not optional, otherwise we put a `<NULL>` in the result table (for now, see Issue https://github.com/google/badwolf/issues/124). 
To illustrate, given a …
> Adjust behavior of TYPE bindings for non-node objects

- bql/planner/data_access.go
- bql/planner/data_access_test.go
- bql/planner/planner_test.go
We have two types of time bindings: `AT` bindings (using the `AT` keyword) and time anchor bindings (eg: `"bought"@[?time]`). 
In both cases, if a graph pattern tries to extract the time anchor from an immutable predicate (like `"parent_of"@[]`) we want to skip this triple and do not show it in the query result (as it does not precisely match the exact graph pattern specified - the pattern required a time anchor). 
Nevertheless, there is one exception: if this graph pattern is marked as `OPTIONAL` we expect to see `<NULL>` in the query result for that time binding.
This PR comes to enforce this behavior.
To illustrate for the case of a `AT` binding, take the query below:
```
SELECT ?p, ?time, ?o
FROM ?test
WHERE {
    /u<peter> ?p AT ?time ?o
};
```
In a `?test` graph having only the two …
> Adjust behavior of AT and time anchor bindings for immutable predicates

- bql/semantic/expression_test.go
- storage/memory/memory_test.go
- tools/testutil/test_util.go
Some functions like `mustBuildLiteral` and `mustBuildPredicate`, previously defined inside "expression_test.go", are useful for other test files as well.
Then, this PR comes to isolate these useful functions in one unique file, "test_util.go", and refactor "expression_test.go" to import these functions from there.
> Create the file "test_util.go"

- tools/testutil/test_util.go
This lib was implemented in PR #144, but it seems that we forgot to add this header comment on it.
> Add header comments to test_util.go

- bql/semantic/expression.go
- bql/semantic/expression_test.go
This PR comes to refactor `expression.go`, mainly renaming some very short variable names to make them more readable and clear for a new developer looking at the file.
> Refactor expression.go to improve readability

- bql/semantic/hooks.go
Minor refactor inside `hooks.go` to rename `f` to `hook` there, as asked by a comment in the PR 146.
> Rename "f" to "hook" in "hooks.go"

- bql/planner/data_access.go
- bql/planner/planner.go
- bql/planner/tracer/trace.go
- tools/vcli/bw/repl/repl.go
This PR comes mainly to structure the current tracer to make it lazily receive, instead of a limited slice of strings, a more flexible struct `tracer.Arguments`. This way it will be much easier in the future to extend it, adding more fields to be passed to the tracer inside the struct, without the need of changing all the other calls for `tracer.Trace` in code.
To illustrate:
```
// Old:
tracer.Trace(p.tracer, func() []string {
return []string{fmt.Sprintf("Processing clause %d: %v", i, &cls)}
})
// Now:
tracer.Trace(p.tracer, func() *tracer.Arguments {
return &tracer.Arguments {
msgs: []string{fmt.Sprintf("Processing clause %d: %v", i, &cls)}
}
})
```
It was deliberately decided to keep the lazy aspect of tracing here, keeping a lambda function as the second parameter for `tracer.Trace` …
> Structure tracer and make it more easily extendible

- bql/grammar/grammar.go
- bql/grammar/grammar_test.go
- bql/lexer/lexer.go
- bql/lexer/lexer_test.go
- bql/semantic/convert.go
- bql/semantic/hooks.go
- bql/semantic/hooks_test.go
- bql/semantic/semantic.go
- bql/semantic/semantic_test.go
This PR comes as the first step on #129, starting to set up a `FILTER` keyword in BadWolf at the grammar, lexer and hooks levels. The first `FILTER` function chosen to be implemented is the `latest` one, to solve what was requested by #86.
It would be very useful to have in BQL a `FILTER` keyword that could allow us to filter out part of the results of a query in a level closer to the storage (closer to the driver), improving performance. This is exactly what this PR starts to introduce, setting up the foundations for this keyword in the grammar, lexer and hooks.
The final objective is to allow the user to specify, inside of `WHERE`, which bindings they want to apply a `FILTER` to, proceeding with a more fine-grained lookup on storage, avoiding unnecessary retrieval of data and optimizing …
> FILTER keyword for latest anchor queries (grammar/lexer/hooks)

- bql/planner/data_access.go
- bql/planner/filter/filter.go
- bql/planner/planner.go
- bql/planner/planner_test.go
- bql/semantic/hooks.go
- bql/semantic/hooks_test.go
- bql/semantic/semantic.go
- bql/semantic/semantic_test.go
- storage/memoization/memoization_test.go
- storage/memory/memory.go
- storage/memory/memory_test.go
- storage/storage.go
This PR comes as a part of #129, finishing to set up a `FILTER` keyword in BadWolf at the planner and memory levels. The first `FILTER` function chosen to be implemented is the `latest` one, solving what was requested by #86.
It would be very useful to have in BQL a `FILTER` keyword that could allow us to filter out part of the results of a query in a level closer to the storage (closer to the driver), improving performance. This is exactly what this PR finishes introducing, completing what started with the PR #149. This PR also showcases the full implementation of how this keyword could work on the driver/storage side as well (exemplified with the changes added to the volatile open-source driver in `memory.go` below).
Then, now the user can specify, inside of `WHERE`, which bindings they …
> FILTER keyword for latest anchor queries (planner/memory)

- bql/planner/filter/filter.go
- bql/planner/planner.go
- bql/planner/planner_test.go
- storage/memory/memory.go
- storage/memory/memory_test.go
This PR comes to add support for the `isImmutable` FILTER function in BadWolf, as detailed in #129. It also comes to help resolving what was requested by #115.
To illustrate its implementation on the driver side, this PR also adds support for this FILTER in the volatile OSS driver (in `memory.go`).
Now, the user can write queries like: 
```
SELECT ?p, ?o
FROM ?test
WHERE {
/u<peter> ?p ?o .
FILTER isImmutable(?p)
};
```
That would return only rows for which the predicate `?p` is not temporal. For other examples of queries have a look at the newly added tests in `planner_test.go`.
This FILTER function also works for object bindings in the clause, along with predicate aliases and object aliases too.
> FILTER isImmutable

- bql/planner/filter/filter.go
- bql/planner/planner.go
- bql/planner/planner_test.go
- storage/memory/memory.go
- storage/memory/memory_test.go
This PR comes to add support for the `isTemporal` FILTER function in BadWolf, as detailed in #129. It also comes to help resolving what was requested by #115.
To illustrate its implementation on the driver side, this PR also adds support for this FILTER in the volatile OSS driver (in `memory.go`).
Now, the user can write queries like: 
```
SELECT ?p, ?o
FROM ?test
WHERE {
/u<peter> ?p ?o .
FILTER isTemporal(?p)
};
```
That would return only rows for which the predicate `?p` is temporal. For other examples of queries have a look at the newly added tests in `planner_test.go`.
This FILTER function also works for object bindings in the clause, along with predicate aliases and object aliases too.
> FILTER isTemporal

- bql/grammar/grammar.go
- bql/grammar/grammar_test.go
- bql/planner/filter/filter.go
- bql/semantic/hooks.go
- bql/semantic/hooks_test.go
Since there will be `FILTER` functions that require a `Value` parameter (such as `greaterThan` in the future), we must have support for a `Value` argument in the BadWolf's grammar for `FILTER` as well. But, at the same time, we must be able to differentiate these `FILTER` functions from others that do not require `Value` (such as `latest`), for a fine-grained error checking.
This PR, then, comes to implement this above, adding support for `Value` in the BadWolf's `FILTER` grammar while also checking its validity at the hooks level.
After this PR, the steps to add support for a new FILTER function become:
1. Add a new enum item in the list of supported filter Operations in `filter.go`;
2. Add a new entry in the `SupportedOperations` map in `filter.go` to map the **lowercase** string of the …
> Add support for FILTER Value at the grammar and hooks levels

- tools/vcli/bw/repl/repl.go
This PR comes to allow the user to have more visibility on latency and memory metrics when using BadWolf, adding support for [pprof](https://github.com/google/pprof) profiling through BadWolf's CLI.
When in the terminal, after already entering the BadWolf's CLI with the command `bw bql`, the user can now write:
```
start profiling;
```
To start `pprof` profiling. The user can also specify the CPU profiling rate with the `-cpurate` flag below:
```
start profiling -cpurate <samples_per_second>
```
Similarly, to stop it they can just write:
```
stop profiling;
```
With profiling enabled, the metrics for latency and memory consumption for the BQLs executed will be printed into two files, `cpuprofile` and `memprofile`, that can then be consumed and visualized through the `go pprof` CLI tool. …
> Support pprof profiling in BadWolf

- bql/planner/data_access.go
- bql/planner/data_access_test.go
- bql/planner/planner.go
- bql/table/table.go
- tools/vcli/bw/repl/repl.go
This PR comes to enhance **debugability** in BadWolf, adding more useful metadata to be traced to help in the occasion of investigating production issues.
To be more precise, this PR comes mainly to add for tracing:
- More **metadata on clause processing** in the planner level (especially the **latency for processing each clause** on the graph pattern and the **overall latency for the entire pattern** as well); 
- The **number of triples returned from driver** for each driver call, along with the **specific name of the graph** being queried during this call and also the **number of rows actually being added to the result table** after that;
- The **number of rows removed from the result table** after processing the **HAVING clause**.
> Add more metadata to tracer to improve debugability

- bql/planner/data_access.go
- bql/planner/planner.go
- bql/planner/tracer/trace.go
- tools/vcli/bw/repl/repl.go
This PR comes to support **different verbosity levels for tracing** in BadWolf, and also to allow the user to customize the current tracing verbosity through the BadWolf's CLI.
This way, it is now possible for the user to control the amount of information they want in the tracing output, accordingly to the use case, and also to control how much of computing power they want to dedicate for tracing.
In the CLI, the syntax for tracing now is:
```
start tracing [-v verbosity_level] [trace_file];
```
With the `-v` flag indicating the global verbosity level to be set for the current tracer.
At the moment, each tracing message in code can be allocated to one of the three following verbosity levels:
- **Level 1:** This level contains the **most crucial** and basic tracing messages to understand …
> Support verbosity levels configuration for tracing

- bql/planner/data_access.go
- bql/planner/planner.go
- tools/vcli/bw/repl/repl.go
This PR comes mainly to:
- Fix problem of **loop variables being passed by reference to the tracing closure** and then having only its last value being shown in the tracing output;
- Fix problem of `lookupOptions` being **passed as a pointer to the tracing closure** (in the "global lookup options" tracing message, for example, another value was being written to the output since the referenced content was changed in the meantime between the call to `.Trace` and the generation of the string message when calling the closure);
- Avoid **unnecessary and more expensive captures** inside the tracing closures (such as capturing an entire `graph` in the closure just to get its `ID` later).
> Fix issues with tracer and improve tracing messages

- bql/planner/planner_test.go
- storage/memory/memory.go
- storage/memory/memory_test.go
Inside the `LookupOptions` struct that arrives on the driver side we have, other than `FilterOptions`, the variables defining the **global time bounds** (`LowerAnchor` and `UpperAnchor` - that are set when using the keywords `BEFORE`, `AFTER` and `BETWEEN`) and also a `MaxElements` variable **limiting** (when set) the **maximum number of elements** for the driver to return.
Since some of these variables are set at the same time, we want to handle them **coherently** and harmoniously with each other, having an **intuitive final behavior**.
For example, given a `?test` graph with the following triples:
```
/u<peter> "bought"@[2016-02-01T00:00:00-08:00] /c<model s>
/u<peter> "bought"@[2016-03-01T00:00:00-08:00] /c<model x>
/u<peter> "bought"@[2016-04-01T00:00:00-08:00] /c<model y>
```
If we …
> Fix behavior when having FILTER options and global lookup options simultaneously

- bql/planner/planner.go
- bql/semantic/expression.go
- bql/semantic/semantic.go
- bql/table/table.go
There are some cases in the codebase where we know the size of slices beforehand.
Thus, we can pre-allocate them instead of relying on append to dynamically increase the slices.
This change decreases the number of times we call runtime.growslice, optimizing the code a bit, and also helps GC.
> Optimize slice allocation in Badwolf.

- storage/storage.go
- triple/literal/literal.go
- triple/node/node.go
- triple/node/node_test.go
- triple/predicate/predicate.go
- triple/predicate/predicate_test.go
- triple/triple.go
- triple/triple_test.go
In most of the cases we know exactly how many bytes we actually need
to copy around, so just copy directly into a properly sized byte slice.
`bytes.Buffer` pre-allocates 64 bytes at minimum, which is more than
we actually use in the majority of cases here since UUIDs are 16 bytes.
> Don't use `bytes.Buffer` unless necessary.

- bql/planner/planner.go
Before this change: planner creates a new goroutine for each row, possibly causing resource exhaustion if there are too many rows.
After this change: planner will only create up to runtime.GOMAXPROCS(0) goroutines, limiting resource usage.
This change is based on the suggested implementation from https://github.com/golang/go/issues/27837.
> Limit concurrency in planner to runtime.GOMAXPROCS(0)

- bql/planner/planner.go
- storage/storage.go
- triple/literal/literal.go
- triple/node/node.go
- triple/triple.go
Because we use `bytes.Buffer` heavily, keep a pool of `bytes.Buffer` objects to reduce allocations. Exception is the triple `UUID` method where we have a fixed sized buffer as it is a concatenation of three `UUID`s.
> Use `sync.Pool` to reduce the number of allocations in `UUID()` method all around

- triple/triple.go
Storing the slice directly causes the value to be placed on the heap
which means an additional allocation.
See: https://staticcheck.io/docs/checks#SA6002
> Store a pointer to slice in `sync.Pool`.
